name: flutter_simulator
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_desktop_cursor: ^0.0.1
  matrix4_transform: ^2.0.1
  path_provider: ^2.0.14
  image: ^4.0.15
  url_launcher: ^6.1.10
  vector_math: ^2.1.4
  window_manager:
    git: 
      url: https://github.com/kekland/window_manager
      ref: 37ae2cf

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
